Adding support for grouped menus
saket/cascade pull request #9
Opened 2020-10-11 10:55 UTC by waseefakhtar

Implementing #1 

### Demo:
<img src="https://user-images.githubusercontent.com/4093820/95676619-d76cb800-0bd8-11eb-928e-2cf1042d8784.gif" width="300"/>

### TODO:
1. `setGroupVisible` currently hides the group but does not adjust the menu height.
2. Adding support for `setGroupCheckable`.
3. `setGroupEnabled` is functional but the group state stays the same. (Perhaps we could add color states for disabled items)

Also, it'd be nice to add icons for the sample grouped menu items. I can add them if there's an icon set you've already used for the other items that I can have access to.

2020-10-15 06:50 UTC, saket requested changes
> setGroupVisible currently hides the group but does not adjust the menu height.

Can you explain more? Why does the popup height change?

> Adding support for setGroupCheckable

Let's leave this for now

> setGroupEnabled is functional but the group state stays the same. (Perhaps we could add color states for disabled items)

What does `PopupMenu` do here?

2020-10-15 06:50 UTC, saket commented on cascade/src/main/java/me/saket/cascade/CascadeMenuAdapter.kt
> +  private val menu: Menu,
This line has changed on `trunk`, can you rebase?

2020-10-15 06:50 UTC, saket commented on cascade/src/main/java/me/saket/cascade/CascadeMenuAdapter.kt
> +    return (menu as MenuBuilder).isGroupDividerEnabled && currGroupId != prevGroupId
Let's early return if `isGroupDividerEnabled` is false?

2020-10-15 06:50 UTC, saket commented on cascade/src/main/java/me/saket/cascade/CascadePopupMenu.kt
> +  defStyleAttr: Int = android.R.style.Widget_Material_PopupMenu
This is unrelated to this PR, can you remove?

2020-10-15 06:50 UTC, saket commented on cascade/src/main/java/me/saket/cascade/MenuItemViewHolder.kt
> +  fun render(item: MenuItemImpl, isGroupDividerEnabled: Boolean) {
Let's rename this to `showDivider`?

2020-10-15 06:50 UTC, saket commented on sample/src/main/java/me/saket/cascade/sample/MainActivity.kt
> +private const val GROUP_ID: Int = 1234
Let's inline this. A class property isn't needed.

2020-10-15 06:50 UTC, saket commented on sample/src/main/java/me/saket/cascade/sample/MainActivity.kt
> +      add(GROUP_ID, Menu.NONE, Menu.NONE, "Filter By")
nit:
- Sort ~By~ by
- Filter ~By~ by

(to match other items)

2020-10-15 19:55 UTC, waseefakhtar commented
> > setGroupVisible currently hides the group but does not adjust the menu height.
> 
> Can you explain more? Why does the popup height change?

This was the same bug as #12, which we resolved in #13.

> 
> > Adding support for setGroupCheckable
> 
> Let's leave this for now

Sounds good.

> 
> > setGroupEnabled is functional but the group state stays the same. (Perhaps we could add color states for disabled items)
> 
> What does `PopupMenu` do here?

This looks more of an enhancement for styles in `sample` rather than in `cascade`. 

Setting any item disabled keeps it the same visually. So perhaps we just need to add `ColorStateList` for text color and icon's tint in `cascadeMenuStyler`. Not within the scope of this, so let me know if you want me to create an issue and work on it on another PR.

2020-10-16 09:38 UTC, nuhkoca commented
@saket do you see the glitch in title change while animation? It seems clashing. Or has it been changed since the newest commits? You might want to see a new demo.

2020-10-16 19:51 UTC, bojankoma commented
> @saket do you realize the glitch in title change during animation? It seems kinda blinking/clashing. Or has it been changed since the newest commits? You might want to see a new demo. 🤔

I think that glitch comes from Theme.MaterialComponents.

2020-10-16 20:15 UTC, nuhkoca commented
@bojankoma How? Any reason behind this?

2020-10-16 20:24 UTC, saket commented
I assume that's related to #4, which was fixed in `v1.1.0`. Please file an issue if you're still seeing it?

2020-10-16 20:49 UTC, nuhkoca commented
Okay, I gave the forked repository a try and didn't encounter any weird behavior. It might have been resolved with the last release. Thanks!

2020-10-17 08:01 UTC, bojankoma commented
> @bojankoma How? Any reason behind this?

@nuhkoca I think the animations for enter or exit are different. I didn't go deep into codebase but I already noticed some key differences between using Theme.Appcompat and Theme.MaterialComponents as your app theme. 
@saket Please, consider your own bundled anims to get more consistency across the theme engine.

2020-10-20 19:10 UTC, saket commented
@bojankoma Interesting. Possible for you to share a video?

2021-01-31 07:56 UTC, saket commented
Sorry it took me way too long to merge this PR. Thanks for contributing @waseefakhtar!

2021-01-31 07:56 UTC, merged